(
 (nil . ((indent-tabs-mode . nil)
	 (tab-width . 4)
	 (fill-column . 80)
	 (c-basic-offset . 4)
	 ))
 (makefile-mode . ((indent-tabs-mode . t)))
 (haxe-mode . ((indent-tabs-mode . nil)
	 (tab-width . 4)
	 (fill-column . 80)
	 ))
 )
